openapi: 3.0.0
info:
  title: Discord Emojier Integration API
  version: 1.0.0
  description: API for integrating Discord webhooks with Telex to send emoji-enhanced messages.

paths:
  /predict:
    post:
      summary: Predict emojis from text
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: A string of emojis corresponding to the input text.
          content:
            text/plain:
              schema:
                type: string

  /send:
    post:
      summary: Send a message to Discord channels using webhook URLs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  type: object
                  properties:
                    channels:
                      type: array
                      items:
                        type: object
                        properties:
                          webhook_url:
                            type: string
                          format_content:
                            type: boolean
                telex_content:
                  type: object
                  properties:
                    event_name:
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                    username:
                      type: string
      responses:
        '200':
          description: A JSON object indicating the status of the message delivery.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string